#.github/workflows/backup.yml

name: "Yedekleme Islemi"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-backup:
    # TEMİZLİK İŞİ İÇİN GEREKLİ İZİNLER EKLENDİ
    permissions:
      contents: read  # Depoyu okumak için
      actions: write   # Önbelleği silebilmek için
    
    uses: berkayy-atas/marketplace-test-workflow/.github/workflows/reusable-backup-workflow.yml@main
    with:
      backup_path: './'
    secrets:
      activation_code: ${{ secrets.ACTIVATION_CODE }}
      encryption_password: ${{ secrets.ENCRYPTION_KEY }}
