#.github/workflows/backup.yml

name: "Yedekleme Islemi"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Bu iş, doğrudan sizin yeniden kullanılabilir iş akışınızı çağırır.
  # 'steps' anahtar kelimesi kullanılmaz çünkü bu bir iş çağrısıdır, adım değil.
  run-backup:
    # Gerekli minimum izinleri ayarla. Yeniden kullanılabilir iş akışının
    # kodları klonlaması (checkout) için 'contents: read' gereklidir.
    permissions:
      contents: read
    
    # 'uses' anahtar kelimesi doğrudan iş seviyesinde kullanılır ve
    # yeniden kullanılabilir iş akışının yolunu belirtir.
    uses: berkayy-atas/marketplace-test-workflow/.github/workflows/reusable-backup-workflow.yml@main # veya @v1.0.0
    with:
      # Yeniden kullanılabilir iş akışının beklediği girdileri (inputs) burada sağlayın.
      backup_path: './' # Yedeklenecek dosyanın veya dizinin yolu (örneğin tüm depo için './')
    secrets:
      # Gerekli secret'ları yeniden kullanılabilir iş akışına aktarın.
      # Bu secret'lar, kullanıcının kendi deposunun ayarlarında tanımlanmalıdır.
      activation_code: ${{ secrets.ACTIVATION_CODE }}
      encryption_password: ${{ secrets.ENCRYPTION_KEY }}
